### ISSUE TITLE
Saddog - niepoprawne nagrody

### ISSUE THREAD

**Issue by Nimorid** [kroniki-neverwinter/bugs#5]
https://discord.com/channels/752493729289601025/1292207372621840415

**Comment by Nimorid** [comment]
Inny dialog dla postaci, która ukończyła quest, już działa ok.

**Comment by Mefi100** [comment]
Do przetestowania w najnowszej wersji modułu.

**Comment by Nimorid** [comment]
Pięknie działa :)
