### ISSUE TITLE
Wyskakujący opis przestał działać poprawnie po zmianach

### ISSUE THREAD

**Issue by Nimorid** [kroniki-neverwinter/bugs#6]
https://discord.com/channels/752493729289601025/1262694383526875168

**Comment by Mefi100** [comment]
Naprawione. Teraz jak to powinno działać:

1. Prosty wyzwalacz: tekst wyświetlany tylko RAZ na postać, może dawać XP. 
2. Wyzwalacz na rzut: sukces tylko raz na postać, rzut tylko raz na restart, może dawać XP. Ilość prób może być nieograniczona (-1) lub konkretna ilość razy (zmienna `KN_MAX_ATTEMPTS`). 

Do testów dodałem komendę `/reset-txt`, która resetuje zmienne "tekstowe" na postaci (ale nie usuwa limitu 1 rzut na restart).

**Comment by Nimorid** [comment]
Wygląda że wszystko ok :)
